# Data and Model parameters
model:
  sheet_size: (150, 300)
  connectivity_std: 10
  synapses_per_neuron: 32
  num_timesteps: 100
  bias: True
  mm_function: torch_sparse
  sparse_format: torch_sparse
  batch_first: True
  adjacency_matrix_path: connection/sparse.pt
  self_recurrence: True
  input_indices: connection/V1_indices_flat.pt
  output_indices: connection/V4_indices_flat.pt
  activation: relu
# Training parameters
data:
  dir: data
  retina_path: connection/V1_indices.npy
  batch_size: 16
  num_workers: 0
optimizer: 
  fn: sparse_sgd
  lr: 0.001
  momentum: 0.9
criterion: cross_entropy 
wandb: False
train:
  epochs: 30
  log_freq: 50
  model_dir: models