# Data and Model parameters
model:
  sheet_size: [150, 300]
  connectivity_std: 10
  synapses_per_neuron: 32
  num_timesteps: 100
  bias: True
  num_classes: 10
  mm_function: torch_sparse
  sparse_format: torch_sparse
  batch_first: True
  adjacency_matrix_path: null
  self_recurrence: True
  input_indices: connection/V1_indices_flat.pt
  output_indices: connection/V4_indices_flat.pt
  activation: relu
# Training parameters
data:
  dataset: cifar10_v1
  root: data
  retina_path: connection/V1_indices.npy
  batch_size: 16
  num_workers: 8
optimizer: 
  fn: adamw
  lr: 0.001
  momentum: 0.9
  beta1: 0.9
  beta2: 0.999
criterion: cross_entropy
wandb: True
visualize:
  disable: True
  save_path: visualizations/test.gif
  fps: 4
  frames: [0, 20]
train:
  epochs: 30
  log_freq: 50
  model_dir: models
  grad_clip: 
    disable: False
    type: value
    value: 1.0
    fn: native